### ISSUE TITLE
Create react app

### ISSUE THREAD

**Issue by MrNobodyX3** [MrNobodyX3/microwave#1]
- [ ] Create a new react app called "microwave"
- [ ] Push the repo to GitHub by following the image instructions.
<img width="683" alt="Screenshot 2022-09-01 at 11 28 53 AM" src="https://user-images.githubusercontent.com/39644589/187965726-764068b3-a2cd-48f3-b1d4-2528c6846416.png">

**Comment by BitSents** [comment]
created default react app
